// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: csar/authz/v1/authz.proto

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject is the user identifier (e.g., UUID from JWT sub claim).
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// resource is the target resource path (e.g., /api/v1/projects/123).
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// action is the operation being performed (e.g., GET, POST, DELETE).
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// context carries optional key-value attributes for future ABAC extension.
	Context map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// scope_type is the assignment scope: "platform" (global) or "tenant".
	ScopeType string `protobuf:"bytes,5,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	// scope_id identifies the scope instance (e.g., tenant UUID). Empty for platform.
	ScopeId       string `protobuf:"bytes,6,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckAccessRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckAccessRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckAccessRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CheckAccessRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *CheckAccessRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type CheckAccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allowed is true if the subject has permission.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// matched_roles lists the roles that granted access (empty if denied).
	MatchedRoles []string `protobuf:"bytes,2,rep,name=matched_roles,json=matchedRoles,proto3" json:"matched_roles,omitempty"`
	// enriched_headers are key-value pairs to inject into the upstream request
	// (e.g., X-User-Roles, X-Authz-Decision).
	EnrichedHeaders map[string]string `protobuf:"bytes,3,rep,name=enriched_headers,json=enrichedHeaders,proto3" json:"enriched_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckAccessResponse) GetMatchedRoles() []string {
	if x != nil {
		return x.MatchedRoles
	}
	return nil
}

func (x *CheckAccessResponse) GetEnrichedHeaders() map[string]string {
	if x != nil {
		return x.EnrichedHeaders
	}
	return nil
}

type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique role identifier (e.g., "admin", "editor").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description is a human-readable explanation of the role.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// parents are the names of parent roles whose permissions are inherited.
	Parents []string `protobuf:"bytes,3,rep,name=parents,proto3" json:"parents,omitempty"`
	// created_at is the Unix timestamp when the role was created.
	CreatedAt     int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Role) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parents       []string               `protobuf:"bytes,3,rep,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{6}
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{9}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{10}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	ScopeType     string                 `protobuf:"bytes,3,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeId       string                 `protobuf:"bytes,4,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{11}
}

func (x *AssignRoleRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AssignRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AssignRoleRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *AssignRoleRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{12}
}

type RevokeRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	ScopeType     string                 `protobuf:"bytes,3,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeId       string                 `protobuf:"bytes,4,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeRoleRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RevokeRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RevokeRoleRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *RevokeRoleRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type RevokeRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleResponse) Reset() {
	*x = RevokeRoleResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleResponse) ProtoMessage() {}

func (x *RevokeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeRoleResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{14}
}

type ListSubjectRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ScopeType     string                 `protobuf:"bytes,2,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeId       string                 `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubjectRolesRequest) Reset() {
	*x = ListSubjectRolesRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubjectRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubjectRolesRequest) ProtoMessage() {}

func (x *ListSubjectRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubjectRolesRequest.ProtoReflect.Descriptor instead.
func (*ListSubjectRolesRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{15}
}

func (x *ListSubjectRolesRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ListSubjectRolesRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *ListSubjectRolesRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type ListSubjectRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []string               `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubjectRolesResponse) Reset() {
	*x = ListSubjectRolesResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubjectRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubjectRolesResponse) ProtoMessage() {}

func (x *ListSubjectRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubjectRolesResponse.ProtoReflect.Descriptor instead.
func (*ListSubjectRolesResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{16}
}

func (x *ListSubjectRolesResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Permission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the auto-generated unique identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// role is the role this permission belongs to.
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// resource is the URL pattern (supports * and ** wildcards).
	Resource string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	// action is the HTTP method or "*" for any.
	Action        string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{17}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AddPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPermissionRequest) Reset() {
	*x = AddPermissionRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPermissionRequest) ProtoMessage() {}

func (x *AddPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPermissionRequest.ProtoReflect.Descriptor instead.
func (*AddPermissionRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{18}
}

func (x *AddPermissionRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AddPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AddPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPermissionResponse) Reset() {
	*x = AddPermissionResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPermissionResponse) ProtoMessage() {}

func (x *AddPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPermissionResponse.ProtoReflect.Descriptor instead.
func (*AddPermissionResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{19}
}

func (x *AddPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type RemovePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePermissionRequest) Reset() {
	*x = RemovePermissionRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermissionRequest) ProtoMessage() {}

func (x *RemovePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermissionRequest.ProtoReflect.Descriptor instead.
func (*RemovePermissionRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{20}
}

func (x *RemovePermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemovePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePermissionResponse) Reset() {
	*x = RemovePermissionResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermissionResponse) ProtoMessage() {}

func (x *RemovePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermissionResponse.ProtoReflect.Descriptor instead.
func (*RemovePermissionResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{21}
}

type ListRolePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePermissionsRequest) Reset() {
	*x = ListRolePermissionsRequest{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePermissionsRequest) ProtoMessage() {}

func (x *ListRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{22}
}

func (x *ListRolePermissionsRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListRolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePermissionsResponse) Reset() {
	*x = ListRolePermissionsResponse{}
	mi := &file_csar_authz_v1_authz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePermissionsResponse) ProtoMessage() {}

func (x *ListRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_authz_v1_authz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_csar_authz_v1_authz_proto_rawDescGZIP(), []int{23}
}

func (x *ListRolePermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_csar_authz_v1_authz_proto protoreflect.FileDescriptor

const file_csar_authz_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x19csar/authz/v1/authz.proto\x12\rcsar.authz.v1\"\xa2\x02\n" +
	"\x12CheckAccessRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12H\n" +
	"\acontext\x18\x04 \x03(\v2..csar.authz.v1.CheckAccessRequest.ContextEntryR\acontext\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x05 \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\x06 \x01(\tR\ascopeId\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12#\n" +
	"\rmatched_roles\x18\x02 \x03(\tR\fmatchedRoles\x12b\n" +
	"\x10enriched_headers\x18\x03 \x03(\v27.csar.authz.v1.CheckAccessResponse.EnrichedHeadersEntryR\x0fenrichedHeaders\x1aB\n" +
	"\x14EnrichedHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aparents\x18\x03 \x03(\tR\aparents\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"c\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aparents\x18\x03 \x03(\tR\aparents\"=\n" +
	"\x12CreateRoleResponse\x12'\n" +
	"\x04role\x18\x01 \x01(\v2\x13.csar.authz.v1.RoleR\x04role\"'\n" +
	"\x11DeleteRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12DeleteRoleResponse\"$\n" +
	"\x0eGetRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\":\n" +
	"\x0fGetRoleResponse\x12'\n" +
	"\x04role\x18\x01 \x01(\v2\x13.csar.authz.v1.RoleR\x04role\"\x12\n" +
	"\x10ListRolesRequest\">\n" +
	"\x11ListRolesResponse\x12)\n" +
	"\x05roles\x18\x01 \x03(\v2\x13.csar.authz.v1.RoleR\x05roles\"{\n" +
	"\x11AssignRoleRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x03 \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\x04 \x01(\tR\ascopeId\"\x14\n" +
	"\x12AssignRoleResponse\"{\n" +
	"\x11RevokeRoleRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x03 \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\x04 \x01(\tR\ascopeId\"\x14\n" +
	"\x12RevokeRoleResponse\"m\n" +
	"\x17ListSubjectRolesRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x02 \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\"0\n" +
	"\x18ListSubjectRolesResponse\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\"d\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"^\n" +
	"\x14AddPermissionRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"R\n" +
	"\x15AddPermissionResponse\x129\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x19.csar.authz.v1.PermissionR\n" +
	"permission\")\n" +
	"\x17RemovePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18RemovePermissionResponse\"0\n" +
	"\x1aListRolePermissionsRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"Z\n" +
	"\x1bListRolePermissionsResponse\x12;\n" +
	"\vpermissions\x18\x01 \x03(\v2\x19.csar.authz.v1.PermissionR\vpermissions2\xde\a\n" +
	"\fAuthzService\x12T\n" +
	"\vCheckAccess\x12!.csar.authz.v1.CheckAccessRequest\x1a\".csar.authz.v1.CheckAccessResponse\x12Q\n" +
	"\n" +
	"CreateRole\x12 .csar.authz.v1.CreateRoleRequest\x1a!.csar.authz.v1.CreateRoleResponse\x12Q\n" +
	"\n" +
	"DeleteRole\x12 .csar.authz.v1.DeleteRoleRequest\x1a!.csar.authz.v1.DeleteRoleResponse\x12H\n" +
	"\aGetRole\x12\x1d.csar.authz.v1.GetRoleRequest\x1a\x1e.csar.authz.v1.GetRoleResponse\x12N\n" +
	"\tListRoles\x12\x1f.csar.authz.v1.ListRolesRequest\x1a .csar.authz.v1.ListRolesResponse\x12Q\n" +
	"\n" +
	"AssignRole\x12 .csar.authz.v1.AssignRoleRequest\x1a!.csar.authz.v1.AssignRoleResponse\x12Q\n" +
	"\n" +
	"RevokeRole\x12 .csar.authz.v1.RevokeRoleRequest\x1a!.csar.authz.v1.RevokeRoleResponse\x12c\n" +
	"\x10ListSubjectRoles\x12&.csar.authz.v1.ListSubjectRolesRequest\x1a'.csar.authz.v1.ListSubjectRolesResponse\x12Z\n" +
	"\rAddPermission\x12#.csar.authz.v1.AddPermissionRequest\x1a$.csar.authz.v1.AddPermissionResponse\x12c\n" +
	"\x10RemovePermission\x12&.csar.authz.v1.RemovePermissionRequest\x1a'.csar.authz.v1.RemovePermissionResponse\x12l\n" +
	"\x13ListRolePermissions\x12).csar.authz.v1.ListRolePermissionsRequest\x1a*.csar.authz.v1.ListRolePermissionsResponseB4Z2github.com/ledatu/csar-proto/csar/authz/v1;authzv1b\x06proto3"

var (
	file_csar_authz_v1_authz_proto_rawDescOnce sync.Once
	file_csar_authz_v1_authz_proto_rawDescData []byte
)

func file_csar_authz_v1_authz_proto_rawDescGZIP() []byte {
	file_csar_authz_v1_authz_proto_rawDescOnce.Do(func() {
		file_csar_authz_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_csar_authz_v1_authz_proto_rawDesc), len(file_csar_authz_v1_authz_proto_rawDesc)))
	})
	return file_csar_authz_v1_authz_proto_rawDescData
}

var file_csar_authz_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_csar_authz_v1_authz_proto_goTypes = []any{
	(*CheckAccessRequest)(nil),          // 0: csar.authz.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil),         // 1: csar.authz.v1.CheckAccessResponse
	(*Role)(nil),                        // 2: csar.authz.v1.Role
	(*CreateRoleRequest)(nil),           // 3: csar.authz.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),          // 4: csar.authz.v1.CreateRoleResponse
	(*DeleteRoleRequest)(nil),           // 5: csar.authz.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),          // 6: csar.authz.v1.DeleteRoleResponse
	(*GetRoleRequest)(nil),              // 7: csar.authz.v1.GetRoleRequest
	(*GetRoleResponse)(nil),             // 8: csar.authz.v1.GetRoleResponse
	(*ListRolesRequest)(nil),            // 9: csar.authz.v1.ListRolesRequest
	(*ListRolesResponse)(nil),           // 10: csar.authz.v1.ListRolesResponse
	(*AssignRoleRequest)(nil),           // 11: csar.authz.v1.AssignRoleRequest
	(*AssignRoleResponse)(nil),          // 12: csar.authz.v1.AssignRoleResponse
	(*RevokeRoleRequest)(nil),           // 13: csar.authz.v1.RevokeRoleRequest
	(*RevokeRoleResponse)(nil),          // 14: csar.authz.v1.RevokeRoleResponse
	(*ListSubjectRolesRequest)(nil),     // 15: csar.authz.v1.ListSubjectRolesRequest
	(*ListSubjectRolesResponse)(nil),    // 16: csar.authz.v1.ListSubjectRolesResponse
	(*Permission)(nil),                  // 17: csar.authz.v1.Permission
	(*AddPermissionRequest)(nil),        // 18: csar.authz.v1.AddPermissionRequest
	(*AddPermissionResponse)(nil),       // 19: csar.authz.v1.AddPermissionResponse
	(*RemovePermissionRequest)(nil),     // 20: csar.authz.v1.RemovePermissionRequest
	(*RemovePermissionResponse)(nil),    // 21: csar.authz.v1.RemovePermissionResponse
	(*ListRolePermissionsRequest)(nil),  // 22: csar.authz.v1.ListRolePermissionsRequest
	(*ListRolePermissionsResponse)(nil), // 23: csar.authz.v1.ListRolePermissionsResponse
	nil,                                 // 24: csar.authz.v1.CheckAccessRequest.ContextEntry
	nil,                                 // 25: csar.authz.v1.CheckAccessResponse.EnrichedHeadersEntry
}
var file_csar_authz_v1_authz_proto_depIdxs = []int32{
	24, // 0: csar.authz.v1.CheckAccessRequest.context:type_name -> csar.authz.v1.CheckAccessRequest.ContextEntry
	25, // 1: csar.authz.v1.CheckAccessResponse.enriched_headers:type_name -> csar.authz.v1.CheckAccessResponse.EnrichedHeadersEntry
	2,  // 2: csar.authz.v1.CreateRoleResponse.role:type_name -> csar.authz.v1.Role
	2,  // 3: csar.authz.v1.GetRoleResponse.role:type_name -> csar.authz.v1.Role
	2,  // 4: csar.authz.v1.ListRolesResponse.roles:type_name -> csar.authz.v1.Role
	17, // 5: csar.authz.v1.AddPermissionResponse.permission:type_name -> csar.authz.v1.Permission
	17, // 6: csar.authz.v1.ListRolePermissionsResponse.permissions:type_name -> csar.authz.v1.Permission
	0,  // 7: csar.authz.v1.AuthzService.CheckAccess:input_type -> csar.authz.v1.CheckAccessRequest
	3,  // 8: csar.authz.v1.AuthzService.CreateRole:input_type -> csar.authz.v1.CreateRoleRequest
	5,  // 9: csar.authz.v1.AuthzService.DeleteRole:input_type -> csar.authz.v1.DeleteRoleRequest
	7,  // 10: csar.authz.v1.AuthzService.GetRole:input_type -> csar.authz.v1.GetRoleRequest
	9,  // 11: csar.authz.v1.AuthzService.ListRoles:input_type -> csar.authz.v1.ListRolesRequest
	11, // 12: csar.authz.v1.AuthzService.AssignRole:input_type -> csar.authz.v1.AssignRoleRequest
	13, // 13: csar.authz.v1.AuthzService.RevokeRole:input_type -> csar.authz.v1.RevokeRoleRequest
	15, // 14: csar.authz.v1.AuthzService.ListSubjectRoles:input_type -> csar.authz.v1.ListSubjectRolesRequest
	18, // 15: csar.authz.v1.AuthzService.AddPermission:input_type -> csar.authz.v1.AddPermissionRequest
	20, // 16: csar.authz.v1.AuthzService.RemovePermission:input_type -> csar.authz.v1.RemovePermissionRequest
	22, // 17: csar.authz.v1.AuthzService.ListRolePermissions:input_type -> csar.authz.v1.ListRolePermissionsRequest
	1,  // 18: csar.authz.v1.AuthzService.CheckAccess:output_type -> csar.authz.v1.CheckAccessResponse
	4,  // 19: csar.authz.v1.AuthzService.CreateRole:output_type -> csar.authz.v1.CreateRoleResponse
	6,  // 20: csar.authz.v1.AuthzService.DeleteRole:output_type -> csar.authz.v1.DeleteRoleResponse
	8,  // 21: csar.authz.v1.AuthzService.GetRole:output_type -> csar.authz.v1.GetRoleResponse
	10, // 22: csar.authz.v1.AuthzService.ListRoles:output_type -> csar.authz.v1.ListRolesResponse
	12, // 23: csar.authz.v1.AuthzService.AssignRole:output_type -> csar.authz.v1.AssignRoleResponse
	14, // 24: csar.authz.v1.AuthzService.RevokeRole:output_type -> csar.authz.v1.RevokeRoleResponse
	16, // 25: csar.authz.v1.AuthzService.ListSubjectRoles:output_type -> csar.authz.v1.ListSubjectRolesResponse
	19, // 26: csar.authz.v1.AuthzService.AddPermission:output_type -> csar.authz.v1.AddPermissionResponse
	21, // 27: csar.authz.v1.AuthzService.RemovePermission:output_type -> csar.authz.v1.RemovePermissionResponse
	23, // 28: csar.authz.v1.AuthzService.ListRolePermissions:output_type -> csar.authz.v1.ListRolePermissionsResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_csar_authz_v1_authz_proto_init() }
func file_csar_authz_v1_authz_proto_init() {
	if File_csar_authz_v1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_csar_authz_v1_authz_proto_rawDesc), len(file_csar_authz_v1_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csar_authz_v1_authz_proto_goTypes,
		DependencyIndexes: file_csar_authz_v1_authz_proto_depIdxs,
		MessageInfos:      file_csar_authz_v1_authz_proto_msgTypes,
	}.Build()
	File_csar_authz_v1_authz_proto = out.File
	file_csar_authz_v1_authz_proto_goTypes = nil
	file_csar_authz_v1_authz_proto_depIdxs = nil
}
