// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: csar/audit/v1/audit.proto

package auditv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditIngestService_RecordEvent_FullMethodName  = "/csar.audit.v1.AuditIngestService/RecordEvent"
	AuditIngestService_RecordEvents_FullMethodName = "/csar.audit.v1.AuditIngestService/RecordEvents"
)

// AuditIngestServiceClient is the client API for AuditIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuditIngestService accepts audit events for centralized persistence.
type AuditIngestServiceClient interface {
	RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error)
	RecordEvents(ctx context.Context, in *RecordEventsRequest, opts ...grpc.CallOption) (*RecordEventsResponse, error)
}

type auditIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditIngestServiceClient(cc grpc.ClientConnInterface) AuditIngestServiceClient {
	return &auditIngestServiceClient{cc}
}

func (c *auditIngestServiceClient) RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEventResponse)
	err := c.cc.Invoke(ctx, AuditIngestService_RecordEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditIngestServiceClient) RecordEvents(ctx context.Context, in *RecordEventsRequest, opts ...grpc.CallOption) (*RecordEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEventsResponse)
	err := c.cc.Invoke(ctx, AuditIngestService_RecordEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditIngestServiceServer is the server API for AuditIngestService service.
// All implementations must embed UnimplementedAuditIngestServiceServer
// for forward compatibility.
//
// AuditIngestService accepts audit events for centralized persistence.
type AuditIngestServiceServer interface {
	RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error)
	RecordEvents(context.Context, *RecordEventsRequest) (*RecordEventsResponse, error)
	mustEmbedUnimplementedAuditIngestServiceServer()
}

// UnimplementedAuditIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditIngestServiceServer struct{}

func (UnimplementedAuditIngestServiceServer) RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEvent not implemented")
}
func (UnimplementedAuditIngestServiceServer) RecordEvents(context.Context, *RecordEventsRequest) (*RecordEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEvents not implemented")
}
func (UnimplementedAuditIngestServiceServer) mustEmbedUnimplementedAuditIngestServiceServer() {}
func (UnimplementedAuditIngestServiceServer) testEmbeddedByValue()                            {}

// UnsafeAuditIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditIngestServiceServer will
// result in compilation errors.
type UnsafeAuditIngestServiceServer interface {
	mustEmbedUnimplementedAuditIngestServiceServer()
}

func RegisterAuditIngestServiceServer(s grpc.ServiceRegistrar, srv AuditIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditIngestService_ServiceDesc, srv)
}

func _AuditIngestService_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditIngestServiceServer).RecordEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditIngestService_RecordEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditIngestServiceServer).RecordEvent(ctx, req.(*RecordEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditIngestService_RecordEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditIngestServiceServer).RecordEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditIngestService_RecordEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditIngestServiceServer).RecordEvents(ctx, req.(*RecordEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditIngestService_ServiceDesc is the grpc.ServiceDesc for AuditIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "csar.audit.v1.AuditIngestService",
	HandlerType: (*AuditIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordEvent",
			Handler:    _AuditIngestService_RecordEvent_Handler,
		},
		{
			MethodName: "RecordEvents",
			Handler:    _AuditIngestService_RecordEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "csar/audit/v1/audit.proto",
}
