// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: csar/audit/v1/audit.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ScopeType     string                 `protobuf:"bytes,6,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeId       string                 `protobuf:"bytes,7,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	BeforeState   []byte                 `protobuf:"bytes,8,opt,name=before_state,json=beforeState,proto3" json:"before_state,omitempty"`
	AfterState    []byte                 `protobuf:"bytes,9,opt,name=after_state,json=afterState,proto3" json:"after_state,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RequestId     string                 `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,12,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_csar_audit_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_csar_audit_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_csar_audit_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AuditEvent) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditEvent) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *AuditEvent) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *AuditEvent) GetBeforeState() []byte {
	if x != nil {
		return x.BeforeState
	}
	return nil
}

func (x *AuditEvent) GetAfterState() []byte {
	if x != nil {
		return x.AfterState
	}
	return nil
}

func (x *AuditEvent) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuditEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RecordEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AuditEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventRequest) Reset() {
	*x = RecordEventRequest{}
	mi := &file_csar_audit_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventRequest) ProtoMessage() {}

func (x *RecordEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_audit_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventRequest.ProtoReflect.Descriptor instead.
func (*RecordEventRequest) Descriptor() ([]byte, []int) {
	return file_csar_audit_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *RecordEventRequest) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type RecordEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventResponse) Reset() {
	*x = RecordEventResponse{}
	mi := &file_csar_audit_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventResponse) ProtoMessage() {}

func (x *RecordEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_audit_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventResponse.ProtoReflect.Descriptor instead.
func (*RecordEventResponse) Descriptor() ([]byte, []int) {
	return file_csar_audit_v1_audit_proto_rawDescGZIP(), []int{2}
}

type RecordEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventsRequest) Reset() {
	*x = RecordEventsRequest{}
	mi := &file_csar_audit_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventsRequest) ProtoMessage() {}

func (x *RecordEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_audit_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventsRequest.ProtoReflect.Descriptor instead.
func (*RecordEventsRequest) Descriptor() ([]byte, []int) {
	return file_csar_audit_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *RecordEventsRequest) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type RecordEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventsResponse) Reset() {
	*x = RecordEventsResponse{}
	mi := &file_csar_audit_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventsResponse) ProtoMessage() {}

func (x *RecordEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_audit_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventsResponse.ProtoReflect.Descriptor instead.
func (*RecordEventsResponse) Descriptor() ([]byte, []int) {
	return file_csar_audit_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *RecordEventsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_csar_audit_v1_audit_proto protoreflect.FileDescriptor

const file_csar_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x19csar/audit/v1/audit.proto\x12\rcsar.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x03\n" +
	"\n" +
	"AuditEvent\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x04 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x06 \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\a \x01(\tR\ascopeId\x12!\n" +
	"\fbefore_state\x18\b \x01(\fR\vbeforeState\x12\x1f\n" +
	"\vafter_state\x18\t \x01(\fR\n" +
	"afterState\x12\x1a\n" +
	"\bmetadata\x18\n" +
	" \x01(\fR\bmetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_ip\x18\f \x01(\tR\bclientIp\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"E\n" +
	"\x12RecordEventRequest\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.csar.audit.v1.AuditEventR\x05event\"\x15\n" +
	"\x13RecordEventResponse\"H\n" +
	"\x13RecordEventsRequest\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.csar.audit.v1.AuditEventR\x06events\"2\n" +
	"\x14RecordEventsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted2\xc3\x01\n" +
	"\x12AuditIngestService\x12T\n" +
	"\vRecordEvent\x12!.csar.audit.v1.RecordEventRequest\x1a\".csar.audit.v1.RecordEventResponse\x12W\n" +
	"\fRecordEvents\x12\".csar.audit.v1.RecordEventsRequest\x1a#.csar.audit.v1.RecordEventsResponseB4Z2github.com/ledatu/csar-proto/csar/audit/v1;auditv1b\x06proto3"

var (
	file_csar_audit_v1_audit_proto_rawDescOnce sync.Once
	file_csar_audit_v1_audit_proto_rawDescData []byte
)

func file_csar_audit_v1_audit_proto_rawDescGZIP() []byte {
	file_csar_audit_v1_audit_proto_rawDescOnce.Do(func() {
		file_csar_audit_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_csar_audit_v1_audit_proto_rawDesc), len(file_csar_audit_v1_audit_proto_rawDesc)))
	})
	return file_csar_audit_v1_audit_proto_rawDescData
}

var file_csar_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_csar_audit_v1_audit_proto_goTypes = []any{
	(*AuditEvent)(nil),            // 0: csar.audit.v1.AuditEvent
	(*RecordEventRequest)(nil),    // 1: csar.audit.v1.RecordEventRequest
	(*RecordEventResponse)(nil),   // 2: csar.audit.v1.RecordEventResponse
	(*RecordEventsRequest)(nil),   // 3: csar.audit.v1.RecordEventsRequest
	(*RecordEventsResponse)(nil),  // 4: csar.audit.v1.RecordEventsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_csar_audit_v1_audit_proto_depIdxs = []int32{
	5, // 0: csar.audit.v1.AuditEvent.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: csar.audit.v1.RecordEventRequest.event:type_name -> csar.audit.v1.AuditEvent
	0, // 2: csar.audit.v1.RecordEventsRequest.events:type_name -> csar.audit.v1.AuditEvent
	1, // 3: csar.audit.v1.AuditIngestService.RecordEvent:input_type -> csar.audit.v1.RecordEventRequest
	3, // 4: csar.audit.v1.AuditIngestService.RecordEvents:input_type -> csar.audit.v1.RecordEventsRequest
	2, // 5: csar.audit.v1.AuditIngestService.RecordEvent:output_type -> csar.audit.v1.RecordEventResponse
	4, // 6: csar.audit.v1.AuditIngestService.RecordEvents:output_type -> csar.audit.v1.RecordEventsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_csar_audit_v1_audit_proto_init() }
func file_csar_audit_v1_audit_proto_init() {
	if File_csar_audit_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_csar_audit_v1_audit_proto_rawDesc), len(file_csar_audit_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csar_audit_v1_audit_proto_goTypes,
		DependencyIndexes: file_csar_audit_v1_audit_proto_depIdxs,
		MessageInfos:      file_csar_audit_v1_audit_proto_msgTypes,
	}.Build()
	File_csar_audit_v1_audit_proto = out.File
	file_csar_audit_v1_audit_proto_goTypes = nil
	file_csar_audit_v1_audit_proto_depIdxs = nil
}
