// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: csar/notify/v1/notify.proto

package notifyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_URGENT      Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_URGENT":      4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_csar_notify_v1_notify_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_csar_notify_v1_notify_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_csar_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_SITE        Channel = 1
	Channel_CHANNEL_TELEGRAM    Channel = 2
	Channel_CHANNEL_EMAIL       Channel = 3
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_SITE",
		2: "CHANNEL_TELEGRAM",
		3: "CHANNEL_EMAIL",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_SITE":        1,
		"CHANNEL_TELEGRAM":    2,
		"CHANNEL_EMAIL":       3,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_csar_notify_v1_notify_proto_enumTypes[1].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_csar_notify_v1_notify_proto_enumTypes[1]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_csar_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=csar.notify.v1.Priority" json:"priority,omitempty"`
	Recipients    []string               `protobuf:"bytes,8,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Channels      []Channel              `protobuf:"varint,9,rep,packed,name=channels,proto3,enum=csar.notify.v1.Channel" json:"channels,omitempty"`
	Sender        string                 `protobuf:"bytes,10,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_csar_notify_v1_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_csar_notify_v1_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_csar_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Notification) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Notification) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Notification) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *Notification) GetChannels() []Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *Notification) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_csar_notify_v1_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_notify_v1_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_csar_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationRequest) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_csar_notify_v1_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_notify_v1_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_csar_notify_v1_notify_proto_rawDescGZIP(), []int{2}
}

type SendNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationsRequest) Reset() {
	*x = SendNotificationsRequest{}
	mi := &file_csar_notify_v1_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationsRequest) ProtoMessage() {}

func (x *SendNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csar_notify_v1_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationsRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_csar_notify_v1_notify_proto_rawDescGZIP(), []int{3}
}

func (x *SendNotificationsRequest) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type SendNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationsResponse) Reset() {
	*x = SendNotificationsResponse{}
	mi := &file_csar_notify_v1_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationsResponse) ProtoMessage() {}

func (x *SendNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csar_notify_v1_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationsResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_csar_notify_v1_notify_proto_rawDescGZIP(), []int{4}
}

func (x *SendNotificationsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_csar_notify_v1_notify_proto protoreflect.FileDescriptor

const file_csar_notify_v1_notify_proto_rawDesc = "" +
	"\n" +
	"\x1bcsar/notify/v1/notify.proto\x12\x0ecsar.notify.v1\"\x9a\x03\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.csar.notify.v1.Notification.MetadataEntryR\bmetadata\x124\n" +
	"\bpriority\x18\a \x01(\x0e2\x18.csar.notify.v1.PriorityR\bpriority\x12\x1e\n" +
	"\n" +
	"recipients\x18\b \x03(\tR\n" +
	"recipients\x123\n" +
	"\bchannels\x18\t \x03(\x0e2\x17.csar.notify.v1.ChannelR\bchannels\x12\x16\n" +
	"\x06sender\x18\n" +
	" \x01(\tR\x06sender\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x17SendNotificationRequest\x12@\n" +
	"\fnotification\x18\x01 \x01(\v2\x1c.csar.notify.v1.NotificationR\fnotification\"\x1a\n" +
	"\x18SendNotificationResponse\"^\n" +
	"\x18SendNotificationsRequest\x12B\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1c.csar.notify.v1.NotificationR\rnotifications\"7\n" +
	"\x19SendNotificationsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted*s\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x04*]\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCHANNEL_SITE\x10\x01\x12\x14\n" +
	"\x10CHANNEL_TELEGRAM\x10\x02\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x032\xe6\x01\n" +
	"\x13NotifyIngestService\x12e\n" +
	"\x10SendNotification\x12'.csar.notify.v1.SendNotificationRequest\x1a(.csar.notify.v1.SendNotificationResponse\x12h\n" +
	"\x11SendNotifications\x12(.csar.notify.v1.SendNotificationsRequest\x1a).csar.notify.v1.SendNotificationsResponseB6Z4github.com/ledatu/csar-proto/csar/notify/v1;notifyv1b\x06proto3"

var (
	file_csar_notify_v1_notify_proto_rawDescOnce sync.Once
	file_csar_notify_v1_notify_proto_rawDescData []byte
)

func file_csar_notify_v1_notify_proto_rawDescGZIP() []byte {
	file_csar_notify_v1_notify_proto_rawDescOnce.Do(func() {
		file_csar_notify_v1_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_csar_notify_v1_notify_proto_rawDesc), len(file_csar_notify_v1_notify_proto_rawDesc)))
	})
	return file_csar_notify_v1_notify_proto_rawDescData
}

var file_csar_notify_v1_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_csar_notify_v1_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_csar_notify_v1_notify_proto_goTypes = []any{
	(Priority)(0),                     // 0: csar.notify.v1.Priority
	(Channel)(0),                      // 1: csar.notify.v1.Channel
	(*Notification)(nil),              // 2: csar.notify.v1.Notification
	(*SendNotificationRequest)(nil),   // 3: csar.notify.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil),  // 4: csar.notify.v1.SendNotificationResponse
	(*SendNotificationsRequest)(nil),  // 5: csar.notify.v1.SendNotificationsRequest
	(*SendNotificationsResponse)(nil), // 6: csar.notify.v1.SendNotificationsResponse
	nil,                               // 7: csar.notify.v1.Notification.MetadataEntry
}
var file_csar_notify_v1_notify_proto_depIdxs = []int32{
	7, // 0: csar.notify.v1.Notification.metadata:type_name -> csar.notify.v1.Notification.MetadataEntry
	0, // 1: csar.notify.v1.Notification.priority:type_name -> csar.notify.v1.Priority
	1, // 2: csar.notify.v1.Notification.channels:type_name -> csar.notify.v1.Channel
	2, // 3: csar.notify.v1.SendNotificationRequest.notification:type_name -> csar.notify.v1.Notification
	2, // 4: csar.notify.v1.SendNotificationsRequest.notifications:type_name -> csar.notify.v1.Notification
	3, // 5: csar.notify.v1.NotifyIngestService.SendNotification:input_type -> csar.notify.v1.SendNotificationRequest
	5, // 6: csar.notify.v1.NotifyIngestService.SendNotifications:input_type -> csar.notify.v1.SendNotificationsRequest
	4, // 7: csar.notify.v1.NotifyIngestService.SendNotification:output_type -> csar.notify.v1.SendNotificationResponse
	6, // 8: csar.notify.v1.NotifyIngestService.SendNotifications:output_type -> csar.notify.v1.SendNotificationsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_csar_notify_v1_notify_proto_init() }
func file_csar_notify_v1_notify_proto_init() {
	if File_csar_notify_v1_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_csar_notify_v1_notify_proto_rawDesc), len(file_csar_notify_v1_notify_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csar_notify_v1_notify_proto_goTypes,
		DependencyIndexes: file_csar_notify_v1_notify_proto_depIdxs,
		EnumInfos:         file_csar_notify_v1_notify_proto_enumTypes,
		MessageInfos:      file_csar_notify_v1_notify_proto_msgTypes,
	}.Build()
	File_csar_notify_v1_notify_proto = out.File
	file_csar_notify_v1_notify_proto_goTypes = nil
	file_csar_notify_v1_notify_proto_depIdxs = nil
}
